version: '3.7'

services:
  cribbage:
    build: ./cribbage
    volumes:
      - ./cribbage/:/code
    ports:
      - 5000:5000
    env_file:
      - cribbage/env.dev
    depends_on:
      - cribbage-redis
  cribbage-redis:
    image: redis