version: '3.7'

services:
  web:
    build: ./web
    volumes:
      - ./web/:/code
    ports:
      - 5000:5000
    env_file:
      - env.dev
    depends_on:
      - redis-master
  redis-master:
    image: redis
