version: '3.7'

services:
  flask:
    build: ./cribbage
    volumes:
      - ./cribbage/:/code
    ports:
      - 5000:5000
    env_file:
      - cribbage/env.dev
    depends_on:
      - redis
  redis:
    image: redis