apiVersion: apps/v1
kind: Deployment
metadata:
  name: cribbage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cribbage
  template:
    metadata:
      labels:
        app: cribbage
    spec:
      containers:
        - name: cribbage
          image: "gcr.io/optimum-pier-280005/cribbage-app:v8"
          env:
            - name: REDISHOST
              valueFrom:
                configMapKeyRef:
                  name: redishost
                  key: REDISHOST
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: cribbage
  labels:
    app: cribbage
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"5000":"cribbage-backendconfig"}}'
spec:
  type: NodePort
  selector:
    app: cribbage
  ports:
  - port: 5000
    protocol: TCP
    name: cribbage-port
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cribbage-ingress
spec:
  backend:
    serviceName: cribbage
    servicePort: cribbage-port
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: cribbage-backendconfig
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 3600