apiVersion: apps/v1
kind: Deployment
metadata:
  name: cribbage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cribbage
  template:
    metadata:
      labels:
        app: cribbage
    spec:
      containers:
        - name: cribbage
          image: "gcr.io/optimum-pier-280005/cribbage-app:v6"
          env:
            - name: REDISHOST
              valueFrom:
                configMapKeyRef:
                  name: redishost
                  key: REDISHOST
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cribbage
spec:
  type: LoadBalancer
  selector:
    app: cribbage
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
